import sampleImg from "./samplimg.jpg";
import sampleImg2 from "./bgimg.jpg";
import sampleImg3 from "./bgmg.jpg";

export const productList = [
  {
    img: sampleImg,
    name: "Classic Leather Brogues",
    price: "$100",
    id: 1,
    sizes: [40, 41, 43, 44, 45],
    description: "Classic brogues for a timeless look",
    searchEng: "brogues, leather",
    otherImgs: [sampleImg, sampleImg2, sampleImg3],
    ratings: 4.5,
  },
  {
    img: sampleImg,
    name: "Stylish Leather Loafers",
    price: "$340",
    id: 9,
    sizes: [40, 41, 43, 44, 45],
    description: "Stylish loafers perfect for formal occasions",
    searchEng: "loafers, leather",
    otherImgs: [sampleImg2, sampleImg3, sampleImg],
    ratings: 4.2,
  },
  {
    img: sampleImg,
    name: "Comfortable Corporate Oxford",
    price: "$1200",
    id: 3,
    sizes: [40, 41, 43, 44, 45],
    description: "Comfortable Oxford shoes for everyday wear",
    searchEng: "oxford, corporate, leather",
    otherImgs: [sampleImg2, sampleImg, sampleImg3],
    ratings: 4.8,
  },
  {
    img: sampleImg,
    name: "Trendy Leather Boots",
    price: "$870",
    id: 4,
    sizes: [40, 41, 43, 44, 45],
    description: "Trendy Chelsea boots for a fashionable look.",
    searchEng: "boots, leather",
    otherImgs: [sampleImg2, sampleImg, sampleImg3],
    ratings: 4.6,
  },
  {
    img: sampleImg,
    name: "Suede  Boots",
    price: "$870",
    id: 43,
    sizes: [40, 41, 43, 44, 45],
    description: "Trendy Chelsea boots for a fashionable look.",
    searchEng: "boots, leather",
    otherImgs: [sampleImg2, sampleImg, sampleImg3],
    ratings: 4.6,
  },
  {
    img: sampleImg,
    name: "Casual Women's Slides",
    price: "$900",
    id: 5,
    sizes: [40, 41, 43, 44, 45],
    description:
      "Casual and classy handmade women sandals perfect for summer outings",
    searchEng:
      "women's slides, slides, casual, leather, female, female+slides, woman+slides",
    otherImgs: [sampleImg2, sampleImg, sampleImg3],
    ratings: 4.3,
  },
  {
    img: sampleImg,
    name: "Vintage Suede Loafers",
    price: "$340",
    id: 12,
    sizes: [40, 41, 43, 44, 45],
    description: "Stylish loafers perfect for formal occasions",
    searchEng: "loafers, leather",
    otherImgs: [sampleImg2, sampleImg, sampleImg3],
    ratings: 4.2,
  },
  {
    img: sampleImg,
    name: "Stylish Men's Slides",
    price: "$870",
    id: 6,
    sizes: [40, 41, 43, 44, 45],
    description:
      "Casual and classy handmade men sandals for a fashionable look.",
    searchEng:
      "men's slides, slides, casual, handmade, male, male+slides, men+slides",
    otherImgs: [sampleImg2, sampleImg, sampleImg3],
    ratings: 4.4,
  },
];
