import sampleImg from "./samplimg.jpg";

export const productList = [
  {
    img: sampleImg,
    name: "brougues",
    price: "$100",
    id: 1,
    sizes: [40, 41, 43, 44, 45],
    description: "Classic brogues for a timeless look",
    otherImgs: [sampleImg, sampleImg, sampleImg, sampleImg],
    category: "brougues",
  },
  {
    img: sampleImg,
    name: "Loafers",
    price: "$340",
    id: 9,
    sizes: [40, 41, 43, 44, 45],
    description: "Stylish loafers perfect for formal occasions",
    otherImgs: [sampleImg, sampleImg, sampleImg, sampleImg],
    category: "loafers",
  },
  {
    img: sampleImg,
    name: "Loafers",
    price: "$340",
    id: 2,
    sizes: [40, 41, 43, 44, 45],
    description: "Stylish loafers perfect for formal occasions",
    otherImgs: [sampleImg, sampleImg, sampleImg, sampleImg],
    category: "loafers",
  },
  {
    img: sampleImg,
    name: "corporate",
    price: "$1200",
    id: 3,
    sizes: [40, 41, 43, 44, 45],
    description: "Comfortable sneakers for everyday wear",
    otherImgs: [sampleImg, sampleImg, sampleImg, sampleImg],
    category: "corporate",
  },
  {
    img: sampleImg,
    name: "boots",
    price: "$870",
    id: 4,
    sizes: [40, 41, 43, 44, 45],
    description: "Trendy Chelsea boots for a fashionable look.",
    otherImgs: [sampleImg, sampleImg, sampleImg, sampleImg],
    category: "boots",
  },
  {
    img: sampleImg,
    name: "Female Slides",
    price: "$900",
    id: 5,
    sizes: [40, 41, 43, 44, 45],
    description: "Casual sandals perfect for summer outings",
    otherImgs: [sampleImg, sampleImg, sampleImg, sampleImg],
    category: "Female Slides",
  },
  {
    img: sampleImg,
    name: "Male Slides",
    price: "$870",
    id: 4,
    sizes: [40, 41, 43, 44, 45],
    description: "Trendy Chelsea boots for a fashionable look.",
    otherImgs: [sampleImg, sampleImg, sampleImg, sampleImg],
    category: "Male Slides",
  },
];
