import sampleImg from "./samplimg.jpg";

export const productList = [
  {
    img: sampleImg,
    name: "brougues",
    price: "$100",
    id: 1,
    sizes: [40, 41, 43, 44, 45],
    description: "Classic brogues for a timeless look",
    searceng: "brougues, leather",
    otherImgs: [sampleImg, sampleImg, sampleImg, sampleImg],
  },
  {
    img: sampleImg,
    name: "Loafers",
    price: "$340",
    id: 9,
    sizes: [40, 41, 43, 44, 45],
    searceng: "Loafers, leather",
    description: "Stylish loafers perfect for formal occasions",
    otherImgs: [sampleImg, sampleImg, sampleImg, sampleImg],
  },
  {
    img: sampleImg,
    name: "Loafers",
    price: "$340",
    id: 2,
    sizes: [40, 41, 43, 44, 45],
    searceng: "Loafers, leather",
    description: "Stylish loafers perfect for formal occasions",
    otherImgs: [sampleImg, sampleImg, sampleImg, sampleImg],
  },
  {
    img: sampleImg,
    name: "corporate",
    price: "$1200",
    id: 3,
    sizes: [40, 41, 43, 44, 45],
    searceng: "oxford , corporate, leather",
    description: "Comfortable corporate for everyday wear",
    otherImgs: [sampleImg, sampleImg, sampleImg, sampleImg],
  },
  {
    img: sampleImg,
    name: "corporate",
    price: "$1200",
    id: 12,
    sizes: [40, 41, 43, 44, 45],
    searceng: "derby, corporate, leather",
    description: "Comfortable derby for everyday wear",
    otherImgs: [sampleImg, sampleImg, sampleImg, sampleImg],
  },
  {
    img: sampleImg,
    name: "boots",
    price: "$870",
    id: 4,
    sizes: [40, 41, 43, 44, 45],
    searceng: "boots, leather",
    description: "Trendy Chelsea boots for a fashionable look.",
    otherImgs: [sampleImg, sampleImg, sampleImg, sampleImg],
  },
  {
    img: sampleImg,
    name: "Female Slides",
    price: "$900",
    id: 5,
    sizes: [40, 41, 43, 44, 45],
    searceng: "womenslides, slides, casual, leather female, women womenslides",
    description:
      "Casual and classy handmade women sandals and slides perfect for summer outings",
    otherImgs: [sampleImg, sampleImg, sampleImg, sampleImg],
  },
  {
    img: sampleImg,
    name: "Male Slides",
    price: "$870",
    id: 4,
    sizes: [40, 41, 43, 44, 45],
    searceng: "menslides, slides, casual, handmade, male, men men+slides",
    description:
      "Casual and classy male handmade sandals and slides for a fashionable look.",
    otherImgs: [sampleImg, sampleImg, sampleImg, sampleImg],
  },
];
